[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name  syslog
    Listen 0.0.0.0
    Port   514
    Mode   udp
    Tag    syslog

[INPUT]
    Name  syslog-nginx
    Listen 0.0.0.0
    Port   51414
    Parser syslog-rfc3164
    Mode   udp
    Tag    nginx.syslog

[OUTPUT]
    Name         forward
    Match        *
    Host         10.163.11.105
    Port         24224

