[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name                    tail
    Path                    /var/lib/docker/containers/*/*.log
    multiline.parser        docker
    Tag                     docker.<container_id>
    Tag_regex               (?<container_id>[^/]+)-json\.log$
    Refresh_Interval        5
    Mem_Buf_Limit           30MB
    Buffer_Chunk_Size       128k
    Buffer_Max_Size         128k
    Skip_Long_Lines         On
    #DB                     /fluent-bit/db/flb_swarmlogs.db

[FILTER]
    Name grep
    Match *
    Exclude log ^ts=.*component=dispatcher

[FILTER]
    Name parser
    Match docker.*
    Key_Name log
    Parser hassio_log
    Reserve_Data True

[FILTER]
    Name     parser
    Match    docker.*
    Key_Name log
    Parser   json

#[FILTER]
#    Name parser
#    Match docker.*
#    Key_Name log
#    Parser java_opensearch_log
#    Reserve_Data True   
#    Multiline On 




#[FILTER]
#    Name     parser
#    Match    *
#    Key_Name log
#    Parser log_parser
#    Reserve_Data True

[OUTPUT]
    Name         forward
    Match        *
    Host         fluentd.comintern.local
    Port         24224
