[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

# --- Common syslog ---
[INPUT]
    Name   syslog
    Listen 0.0.0.0
    Port   514
    Mode   udp
    Parser syslog-rfc3164
    Tag    syslog.general

# --- Separate filter  for nginx ---
[FILTER]
    Name    rewrite_tag
    Match   syslog.general
    Rule    ident ^nginx_access$ nginx.access true

[FILTER]
    Name    rewrite_tag
    Match   syslog.general
    Rule    ident ^nginx_error$ nginx.error true

[FILTER]
    Name    parser
    Match   nginx.access
    Key_Name message
    Parser  nginx_access

[FILTER]
    Name    parser
    Match   nginx.error
    Key_Name message
    Parser  nginx_error

# --- Output Fluentd ---
[OUTPUT]
    Name   forward
    Match  *
    Host   10.163.11.105
    Port   24224