#[PARSER]
#    Name                docker
#    Format              json
#    Time_Key            time
#    Time_Format         %Y-%m-%dT%H:%M:%S.%L
#    Time_Keep           On
#    Decode_Field_As     escaped    log

[PARSER]
    Name        json
    Format      json

[PARSER]
    Name   nginx_access
    Format regex
    Regex  ^(?<remote_addr>\S+) - (?<remote_user>\S+) \[(?<time>[^\]]+)\] "(?<method>\S+) (?<uri>\S+) (?<protocol>[^"]+)" (?<status>\d+) (?<bytes>\d+) "(?<referer>[^"]*)" "(?<agent>[^"]*)"
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z

[PARSER]
    Name   nginx_error
    Format regex
    Regex  ^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<level>\w+)\] (?<pid>\d+)\#(?<tid>\d+): \*(?<connection>\d+) (?<message>.*)$
    Time_Key time
    Time_Format %Y/%m/%d %H:%M:%S

[PARSER]
    Name        java_opensearch_log
    Format      regex
    Regex       ^\[(?<time>[^\]]+)\]\[(?<level>[A-Z]+)\]\[(?<logger>[^\]]+)\] \[(?<node>[^\]]+)\] \[(?<index>[^\]]+)\] (?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S,%L

[PARSER]
    Name        hassio_log
    Format      regex
    Regex       ^(?<level>[A-Z]+):(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d+):(?<logger>[^:]+):(?<message>.*)
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S,%L

[PARSER]
    Name        syslog-rfc3164
    Format      regex
    Regex       ^\<(?<pri>[0-9]+)\>(?<time>[A-Za-z]{3} [ 0-9]{1,2} [0-9:]{8}) (?<host>[^ ]+) (?<ident>[^:]+): (?<message>.*)$
    Time_Key    time
    Time_Format %b %d %H:%M:%S

[PARSER]
    Name        syslog-rfc5424
    Format      regex
    Regex       ^\<(?<pri>[0-9]{1,5})\>(?<version>[0-9]+) (?<time>[^ ]+) (?<host>[^ ]+) (?<app>[^ ]+) (?<procid>[^ ]+) (?<msgid>[^ ]+) (?<sd>(?:\[[^\]]*\]|-)+) ?(?<message>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S
    Time_Keep   On 

[PARSER]
    Name   log_parser
    Format regex
    Regex  ^\s*(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \+\d{4} \[(?<level>\w+)\]: (?<message>.*)
    Time_Key time
    Time_Format %Y-%m-%d %H:%M:%S
