pipeline {
    agent { label 'cloud && hetzner' }

    parameters {
        booleanParam(name: 'FORCE_REDEPLOY', defaultValue: false, description: 'Force redeployment of stack even if no changes detected')
    }

    environment {
        DOCKER_STACK_NAME = 'portainer'
        DOCKER_COMPOSE_DIR = 'docker-portainer' // Path to docker-compose.yml
        DOCKER_COMPOSE_FILE = 'portainer-agent-stack.yml'
        IMAGE_VERSION = "${params.PORTAINER_VERSION}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                url: 'https://github.com/nazmang/docker.git'
            }
        }

        stage('Create Files') {
            when {
                anyOf {
                    changeset "**/${env.DOCKER_COMPOSE_DIR}/**"
                    expression { params.FORCE_REDEPLOY }
                }
            }  
            steps {
                script {
                    def composeDir = "${env.WORKSPACE}/${env.DOCKER_COMPOSE_DIR}"
                    // Create .env file with parameters in DOCKER_COMPOSE_DIR
                    def startEnv = """
                    PORTAINER_VERSION=${env.IMAGE_VERSION}
                    """
                    writeFile file: "${composeDir}/.env", text: startEnv.trim()
                }
            }
        }

        stage('Deploy stack') {
            when {
                anyOf {
                    changeset "**/${env.DOCKER_COMPOSE_DIR}/**"
                    expression { params.FORCE_REDEPLOY }
                }
            }  
            steps {
                dir("${env.DOCKER_COMPOSE_DIR}") {
                    sh """
                        # Export environment variables from .env file
                        export \$(grep -v '^#' .env | xargs -d '\\n')

                        # Deploy Docker stack
                        envsubst < ${env.DOCKER_COMPOSE_FILE} | docker stack deploy -c - ${env.DOCKER_STACK_NAME}
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}