@Library('jenkins-telegram-notify') _

def deployExecuted = false

pipeline {
    agent { label 'cloud && hetzner' } // Ensure the agent has Docker and Swarm mode enabled
    parameters {
        booleanParam(name: 'FORCE_DEPLOY', defaultValue: false, description: 'Force deployment ignoring changeset')
    }
    environment {
        // Define environment variables for the stack
        DOCKER_STACK_NAME = 'fluentd'
        DOCKER_COMPOSE_DIR = 'docker-fluentd' // Path to docker-compose.yml
        DOCKER_COMPOSE_FILE = 'docker-compose.yml' // Name of your main Docker Compose file
        // Telegram configre
        TELEGRAM_BOT_TOKEN = credentials('telegramToken')
        TELEGRAM_CHAT_ID = credentials('telegramChatid')
        OS_PASSWORD = "${params.OS_PASSWORD}"
    }

    stages {
        stage('Create Files') {
            when {
                anyOf {
                    changeset "**/${env.DOCKER_COMPOSE_DIR}/**"
                    expression { return params.FORCE_DEPLOY }
                }
            }
            steps {
                script {
                    def composeDir = "${env.WORKSPACE}/${env.DOCKER_COMPOSE_DIR}"
                    def envContent = """
                    OS_PASSWORD=${env.OS_PASSWORD}
                    """
                    // echo "Generated .env content:\n${envContent}"
                    writeFile file: "${composeDir}/.env", text: envContent
                }
            }
        }
        stage('Docker Login') {
            when {
                anyOf {
                    changeset "**/${env.DOCKER_COMPOSE_DIR}/**"
                    expression { return params.FORCE_DEPLOY }
                }
            }
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    """
                }
            }
        }
        stage('Deploy Fluentd Stack') {
            when {
                anyOf {
                    changeset "**/${env.DOCKER_COMPOSE_DIR}/**"
                    expression { return params.FORCE_DEPLOY }
                }
            }
            steps {
                script {
                    dir("${env.DOCKER_COMPOSE_DIR}") {
                        // Deploy the stack using docker stack deploy
                        sh "make -f Makefile -e deploy-all STACK_NAME=${env.DOCKER_STACK_NAME} CONF_VERSION=${BUILD_NUMBER}"
                    }
                    deployExecuted = true
                }
            }
        }
    }

    post {
        success {
            script {
                if (deployExecuted) {
                    def message = '✅ <b>Fluentd Deploy Success</b>\n' +
                                  "Job: ${env.JOB_NAME}\n" +
                                  "Build: #${env.BUILD_NUMBER}\n" +
                                  "Stack: ${env.DOCKER_STACK_NAME}\n" +
                                  "URL: <a href=\"${env.BUILD_URL}\">Link</a>"
                    telegram.sendMessage(env.TELEGRAM_BOT_TOKEN, env.TELEGRAM_CHAT_ID, message, 'HTML')
                } else {
                    echo 'Deploy stack was not executed, skipping Telegram notification.'
                }
            }
        }
        failure {
            script {
                def message = '❌ <b>Fluentd Deploy Failed</b>\n' +
                          "Job: ${env.JOB_NAME}\n" +
                          "Build: #${env.BUILD_NUMBER}\n" +
                          "Stack: ${env.DOCKER_STACK_NAME}\n" +
                          "URL: <a href=\"${env.BUILD_URL}\">Link</a>"
                telegram.sendMessage(env.TELEGRAM_BOT_TOKEN, env.TELEGRAM_CHAT_ID, message, 'HTML')
            }
        }
        always {
            cleanWs()
        }
    }
}
