services:
  app:
    image: "jc21/nginx-proxy-manager:2.12.3"
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

volumes:
  data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NGINXP_DATA_PATH}"
  letsencrypt:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NGINXP_LETSENCRYPT_PATH}"
