version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:${CLOUDFLARED_TAG:-latest}
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    networks:
      - jenkins_net

networks:
  jenkins_net:
    name: jenkins_jenkins_net
    external: true
