version: "3.8"

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - jenkins_net
    volumes:
      - etcd_data:/bitnami/etcd

networks:
  jenkins_net:
    name: jenkins_jenkins_net
    external: true

volumes:
  etcd_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${ETCD_DATA_PATH}"
