version: '3.7'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "44443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - cert:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - jenkins_jenkins_net

  acme-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: acme-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_NETWORK=jenkins_jenkins_net
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - cert:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nginx-proxy
    networks:
      - jenkins_jenkins_net

networks:
  jenkins_jenkins_net:
    external: true

volumes:
  nginx_conf:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas,rw,noatime,nfsvers=3"
      device: ":/mnt/trash_pool/misc/nginx_conf"
  cert:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas,rw,noatime,nfsvers=3"
      device: ":/mnt/trash_pool/misc/nginx_conf/certs"
  vhost:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas,rw,noatime,nfsvers=3"
      device: ":/mnt/trash_pool/misc/nginx_conf/vhost"
  html:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas,rw,noatime,nfsvers=3"
      device: ":/mnt/trash_pool/misc/nginx_conf/html"
