http.port: 9200
network.host: 0.0.0.0
network.publish_host: _eth0_
cluster.name: opensearch-cluster
bootstrap.memory_lock: true
plugins.security.restapi.roles_enabled:
  ["all_access", "security_rest_api_access"]
plugins.security.ssl.transport.enabled_protocols:
  - "TLSv1.2"
plugins.security.ssl.http.enabled_protocols:
  - "TLSv1.2"
plugins.security.ssl.transport.pemcert_filepath: certs/node.pem
plugins.security.ssl.transport.pemkey_filepath: certs/node-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: certs/ca.pem

plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: certs/node.pem
plugins.security.ssl.http.pemkey_filepath: certs/node-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: certs/ca.pem

plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false
plugins.security.allow_default_init_securityindex: true

plugins.security.nodes_dn:
  - "CN=opensearch-node,OU=IT,O=MyOrg,L=City,ST=State,C=US"
plugins.security.authcz.admin_dn:
  - "CN=opensearch-node,OU=IT,O=MyOrg,L=City,ST=State,C=US"
