version: '3.1'

services:

  nodeexporter:
    image: prom/node-exporter:v1.0.1
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"  
      
  prometheus:
    image: prom/prometheus:v2.20.0
    container_name: prometheus
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"    
      
networks:
  monitor-net:
  
volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.56,rsize=32768,wsize=32768,timeo=300,tcp,rw,noatime"
      device: ":/mnt/big_pool/misc/prometheus_data"      
  prometheus_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.56,rsize=32768,wsize=32768,timeo=300,tcp,rw,noatime"
      device: ":/mnt/big_pool/misc/prometheus_config"
