---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /your/local/assets/:/www/assets
    ports:
      - 8012:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default

volumes:
  homer:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas,vers=3,rsize=65536,wsize=65536,timeo=300,tcp,rw,noatime"
      device: ":/mnt/vm_pool/misc/homer"  