{
 "title": "Cert Manager",
 "tags": [
  "cert-manager",
  "infra"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Certificates Ready",
   "type": "stat",
   "description": "The number of certificates in the ready state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition) (certmanager_certificate_ready_status)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Soonest Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(certmanager_certificate_expiration_timestamp_seconds > 0) - time()"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "description": "Status of the certificates. Values are True, False or Unknown.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(avg by (name, namespace, condition, exported_namespace) (certmanager_certificate_ready_status == 1), \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(avg by (name, namespace, exported_namespace) (certmanager_certificate_expiration_timestamp_seconds) * 1000, \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    }
   ]
  },
  {
   "title": "Controller Sync Requests/sec",
   "type": "timeseries",
   "description": "The rate of controller sync requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(certmanager_controller_sync_call_count[$__rate_interval])\n)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "ACME HTTP Requests/sec",
   "type": "timeseries",
   "description": "Rate of requests to ACME provider.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, path, status) (\n  rate(certmanager_http_acme_client_request_count[$__rate_interval])\n)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "ACME HTTP Request avg duration",
   "type": "timeseries",
   "description": "Average duration of requests to ACME provider. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, path, status) (rate(certmanager_http_acme_client_request_duration_seconds_sum[$__rate_interval]))\n/\nsum by (method, path, status) (rate(certmanager_http_acme_client_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  }
 ]
}