version: '3.3'
services:
 transmission:
  image: haugene/transmission-openvpn:5.2
  ports:
    - "9091:9091"
    - "1888:1888"
    - "51413:51413"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - Install:/Install
    - Movies:/Movies
    - Serials:/Serials
    - transmission_data:/data
    - transmission_config:/config
  environment:
    - PEER_DNS=true
    - CREATE_TUN_DEVICE=true
    - WEBPROXY_ENABLED=true
    - WEBPROXY_PORT=1888
  env_file:
    - vpn.env
  cap_add:
    - NET_ADMIN
  logging:
    driver: json-file
    options:
      max-size: 10m
  healthcheck:
    test: ["CMD-SHELL", "curl -sS http://localhost:9091/transmission/web/ || exit 1"]
    interval: 120s
    timeout: 30s
    retries: 5     
  sysctls:
    - "net.ipv6.conf.all.disable_ipv6=0"
  restart: unless-stopped

networks:
  default:      
    ipam:
      driver: default
      config:
        - subnet: "10.123.234.0/24"

volumes:
  Install:
    driver: local 
    driver_opts:
      type: "nfs"
      o: "addr=nas,rsize=65536,wsize=65536,timeo=300,tcp,rw,noatime"
      device: ":/mnt/big_pool/Install"
  Movies:
    driver: local 
    driver_opts:
      type: "nfs"
      o: "addr=nas,rsize=65536,wsize=65536,timeo=300,tcp,rw,noatime"
      device: ":/mnt/trash_pool/Movies"
  Serials:
    driver: local 
    driver_opts:
      type: "nfs"
      o: "addr=nas,rsize=65536,wsize=65536,timeo=300,tcp,rw,noatime"
      device: ":/mnt/trash_pool/old_data/f/Acht"
  transmission_data:
    driver: local 
    driver_opts:
      type: "nfs"
      o: "addr=nas,rsize=65536,wsize=65536,timeo=300,tcp,rw,noatime"
      device: ":/mnt/trash_pool/old_data/"
  transmission_config:
    driver: local 
    driver_opts:
      type: "nfs"
      o: "addr=nas,rsize=65536,wsize=65536,timeo=300,tcp,rw,noatime,nfsvers=4"
      device: ":/mnt/trash_pool/old_data/.config"
