version: '3.8'

services:
   
  postgres-zabbix:
    image: postgres:12-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.platform.arch==x86_64"
    env_file:
      - start.env       
    expose:
      - '5433'
    restart: always
    volumes:
      - zabbix-db:/var/lib/postgresql/data
    networks:
      - zabbix-net
 

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    environment:
      DB_SERVER_HOST: postgres-zabbix
      DB_SERVER_PORT: 5432
    env_file:
      - start.env      
    ports:
       - '10051:10051'
    restart: always
    links: 
      - postgres-zabbix
    depends_on:
      - postgres-zabbix
    networks:
      - zabbix-net  

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: postgres-zabbix
      DB_SERVER_PORT: 5432 
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Kiev
    env_file:
      - start.env  
    ports:
      - '18080:8080'
      - '18443:8443'
    restart: always
    links: 
      - zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net  
      
networks:
  zabbix-net:
  
volumes:
  zabbix-db:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.2.56,rsize=65536,wsize=65536,timeo=300,tcp,rw,noatime"
      device: ":/mnt/big_pool/misc/zabbix_db"  
  
