def deployExecuted = false // Flag indicates when stack deploy is successful

pipeline {
    agent {label 'cloud && hetzner'}
    
    environment {
        DOCKER_STACK_NAME = 'zabbix' 
        DOCKER_COMPOSE_DIR = 'docker-zabbix' // Path to stack files
        DOCKER_CONTEXT='default' 
        // Telegram configre
        TELEGRAM_BOT_TOKEN = credentials('telegramToken')
        TELEGRAM_CHAT_ID = credentials('telegramChatid')         
    }
    
    stages {
        stage('Create Files') {
            when {
                changeset "**/${env.DOCKER_COMPOSE_DIR}/**"
            }
            steps {
                script {
                    def composeDir = "${env.WORKSPACE}/${env.DOCKER_COMPOSE_DIR}"
                    // Create .POSTGRES_USER and .POSTGRES_PASSWORD files in DOCKER_COMPOSE_DIR
                    writeFile file: "${composeDir}/.POSTGRES_USER", text: env.POSTGRES_USER
                    writeFile file: "${composeDir}/.POSTGRES_PASSWORD", text: env.POSTGRES_PASSWORD

                    // Create start.env file with parameters in DOCKER_COMPOSE_DIR
                    def startEnv = """
                    POSTGRES_DB=${params.POSTGRES_DB}
                    POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
                    POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
                    DB_SERVER_HOST=${params.POSTGRES_HOST}
                    DB_SERVER_PORT=5432
                    ZBX_SERVER_HOST=zabbix-server
                    ZBX_STARTVMWARECOLLECTORS=1
                    PHP_TZ=Europe/Kiev
                    PGUSER=${params.POSTGRES_USER}
                    PGHOST=${params.POSTGRES_HOST}
                    PGPORT=5432
                    DATA_SOURCE_URI=${params.POSTGRES_HOST}?sslmode=disable
                    """
                    writeFile file: "${composeDir}/start.env", text: startEnv
                }
            }
        }
        stage('Deploy stack'){    
            when {
                changeset "**/${env.DOCKER_COMPOSE_DIR}/**"
            }        
            steps {                
                script {
                    def composeFile = "docker-compose.yml"
                   
                    // Check if EXTERNAL_POSTGRES is 'true' and adjust compose file accordingly
                    if (params.EXTERNAL_POSTGRES.toBoolean() == true) {
                        composeFile = "docker-compose-nopsql.yml"                        
                    }

                    dir("${env.DOCKER_COMPOSE_DIR}") {
                        sh  """
                                docker context use ${env.DOCKER_CONTEXT}
                                CONF_VERSION=${BUILD_NUMBER} docker stack deploy -c ${composeFile} ${env.DOCKER_STACK_NAME}
                            """ 
                        
                    }
                    deployExecuted = true
                    echo "Deploy executed: ${deployExecuted}"
                }
            }
        }
        
    }
    post {
        always { 
            cleanWs()
        }
        success {
            script{
                // Cleanup orphaned secrets
                sh  """
                    docker secret ls --format '{{.Name}}'  \
                    | awk '/^POSTGRES_/ && !/^(POSTGRES_PASSWORD_v${BUILD_NUMBER}|POSTGRES_USER_v${BUILD_NUMBER})\$/{print}' \
                    | xargs -I {} docker secret rm {} || true
                """
                
                if (deployExecuted) {
                    def message = "✅ *Jenkins Deploy Success*\n" +
                                  "Job: ${env.JOB_NAME}\n" +
                                  "Build: #${env.BUILD_NUMBER}\n" +
                                  "Stack: ${env.DOCKER_STACK_NAME}\n" +
                                  "URL: ${env.BUILD_URL}"
                    sh """
                        curl -s -X POST https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage \
                        -d chat_id=${env.TELEGRAM_CHAT_ID} \
                        -d text="${message}" \
                        -d parse_mode=HTML
                    """
                } else {
                    echo "Deploy stack was not executed, skipping Telegram notification."
                }
            }
        }
        failure {
            script {
                def message = "<b>❌ Jenkins Deploy Failed</b>\n" +
                          "Job: ${env.JOB_NAME}\n" +
                          "Build: #${env.BUILD_NUMBER}\n" +
                          "Stack: ${env.DOCKER_STACK_NAME}\n" +
                          "URL: <a href='${env.BUILD_URL}'>Link</a>"
                sh """
                    curl -s -X POST https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage \
                    -d chat_id=${env.TELEGRAM_CHAT_ID} \
                    -d text="${message}" \
                    -d parse_mode=HTML
                """
            }
        }
    }
}